#!/usr/bin/env python

import roslib; roslib.load_manifest('cv_nodes')
import rospy
import numpy
import cv_bridge
import cv
import cv2
import time

import sensor_msgs

bridge = cv_bridge.CvBridge()

def receive_image(msg):
    cv2.imshow("window", numpy.asarray(bridge.imgmsg_to_cv(msg)[:,:]))

if __name__ == "__main__":
    rospy.init_node("imshow", anonymous=True)
    sub_image = rospy.Subscriber("image", sensor_msgs.msg.Image, receive_image)
    cv2.namedWindow("window")
    while not rospy.is_shutdown():
        time.sleep(0)
        cv2.waitKey(1)

